import {
  Activity,
  Children,
  Consumables,
  Drinking,
  Ethnicity,
  Gender,
  Income,
  LevelOfEducation,
  MaritalStatus,
  PoliticalBeliefs,
  Purity,
  Religion,
  WeightUnit,
  YesNoOrUnknown,
} from "@prisma/client";
import { CircleSchemaType } from "../../src/schemas/Circle";
import { countries } from "../../src/globals/location";

export const Circles = {
  Religion: {
    Christianity: {
      id: "1",
      label: "Christianity",
      name: Religion.CHRISTIANITY,
      religionRestriction: [Religion.CHRISTIANITY],
    } as CircleSchemaType,
    Athiesm: {
      id: "2",
      label: "Athiesm",
      name: Religion.ATHEISM,
      religionRestriction: [Religion.ATHEISM],
    } as CircleSchemaType,
    Agnosticism: {
      id: "3",
      label: "Agnosticism",
      name: Religion.AGNOSTICISM,
      religionRestriction: [Religion.AGNOSTICISM],
    } as CircleSchemaType,
    Buddhism: {
      id: "4",
      label: "Buddhism",
      name: Religion.BUDDHISM,
      religionRestriction: [Religion.BUDDHISM],
    } as CircleSchemaType,
    Mormonism: {
      id: "5",
      label: "Mormonism",
      name: Religion.MORMONISM,
      religionRestriction: [Religion.MORMONISM],
    } as CircleSchemaType,
    Hinduism: {
      id: "6",
      label: "Hinduism",
      name: Religion.HINDUISM,
      religionRestriction: [Religion.HINDUISM],
    } as CircleSchemaType,
    Judaism: {
      id: "7",
      label: "Judaism",
      name: Religion.JUDAISM,
      religionRestriction: [Religion.JUDAISM],
    } as CircleSchemaType,
    Spiritual: {
      id: "8",
      label: "Other/Spiritual",
      name: Religion.OTHER,
      religionRestriction: [Religion.OTHER],
    } as CircleSchemaType,
  },
  Political: {
    Conservative: {
      id: "9",
      label: "Conservativism",
      name: PoliticalBeliefs.CONSERVATIVE,
      politicalBeliefsRestriction: [PoliticalBeliefs.CONSERVATIVE],
    } as CircleSchemaType,
    Moderate: {
      id: "10",
      label: "Moderatism",
      name: PoliticalBeliefs.MODERATE,
      politicalBeliefsRestriction: [PoliticalBeliefs.MODERATE],
    } as CircleSchemaType,
    Liberal: {
      id: "11",
      label: "Liberalism",
      name: PoliticalBeliefs.LIBERAL,
      politicalBeliefsRestriction: [PoliticalBeliefs.LIBERAL],
    } as CircleSchemaType,
    Independent: {
      id: "12",
      label: "Independent",
      name: PoliticalBeliefs.INDEPENDENT,
      politicalBeliefsRestriction: [PoliticalBeliefs.INDEPENDENT],
    } as CircleSchemaType,
  },
  Continent: {
    NorthAmerica: {
      id: "15",
      label: "North America",
      name: "North America",
      continentRestriction: ["North America"],
    } as CircleSchemaType,
    SouthAmerica: {
      id: "16",
      label: "South America",
      name: "South America",
      continentRestriction: ["South America"],
    } as CircleSchemaType,
    Europe: {
      id: "17",
      label: "Europe",
      name: "Europe",
      continentRestriction: ["Europe"],
    } as CircleSchemaType,
    Australia: {
      id: "18",
      label: "Australia",
      name: "Australia",
      continentRestriction: ["Australia"],
    } as CircleSchemaType,
    Asia: {
      id: "19",
      label: "Asia",
      name: "Asia",
      continentRestriction: ["Asia"],
    } as CircleSchemaType,
    Antarctica: {
      id: "20",
      label: "Antarctica",
      name: "Antarctica",
      continentRestriction: ["Antarctica"],
    } as CircleSchemaType,
    Africa: {
      id: "21",
      label: "Africa",
      name: "Africa",
      continentRestriction: ["Africa"],
    } as CircleSchemaType,
  },
};

export const CirclesList = [
  Circles.Religion.Athiesm,
  Circles.Religion.Agnosticism,
  Circles.Religion.Buddhism,
  Circles.Religion.Christianity,
  Circles.Religion.Hinduism,
  Circles.Religion.Judaism,
  Circles.Religion.Mormonism,
  Circles.Religion.Spiritual,
  Circles.Political.Conservative,
  Circles.Political.Moderate,
  Circles.Political.Liberal,
  Circles.Political.Independent,
  Circles.Continent.NorthAmerica,
  Circles.Continent.SouthAmerica,
  Circles.Continent.Antarctica,
  Circles.Continent.Australia,
  Circles.Continent.Asia,
  Circles.Continent.Europe,
  Circles.Continent.Africa,
];

export const Users = [
  {
    userId: "1",
    username: "Jeremiah",
    sex: Gender.MALE,
    birthDate: new Date(1999, 4, 24),
    weight: 80.23,
    height: 198,
    location: {
      id: "20",
      country: countries[20].country,
      continent: countries[20].continent,
      state: countries[20].states[0],
    },
    willingToRelocate: YesNoOrUnknown.YES,
    children: Children.HAS_NOT_AND_DOES_WANT,
    ethnicity: Ethnicity.WHITE,
    drinking: Drinking.NEVER,
    consumables: Consumables.NO_CONSUMABLES,
    politicalBeliefs: PoliticalBeliefs.CONSERVATIVE,
    levelOfEducation: LevelOfEducation.BACHELORS,
    purity: Purity.VIRGIN_WAITING,
    onlyLookingForTraditionalHousehold: YesNoOrUnknown.YES,
    income: Income.SINGLE,
    maritalStatus: MaritalStatus.NEVER_MARRIED,
    activity: Activity.INFREQUENT,
    religion: Religion.CHRISTIANITY,
    bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum!",
    weightUnit: WeightUnit.KG,
    circles: [Circles.Religion.Christianity, Circles.Political.Conservative],
    password: "password1234",
    email: "email@gmail.com",
    interactions: [
      {
        initiatedUserId: "1",
        affectedUserId: "3",
        isLiked: false,
        isBlocked: false,
      },
    ],
    affections: [
      {
        initiatedUserId: "2",
        affectedUserId: "1",
        isLiked: true,
        isBlocked: false,
      },
    ],
  },
  {
    userId: "2",
    username: "Tina 2.0",
    sex: Gender.FEMALE,
    birthDate: new Date(1998, 2, 24),
    weight: 80.23,
    height: 198,
    location: {
      id: "20",
      country: countries[20].country,
      continent: countries[20].continent,
      state: countries[20].states[0],
    },
    willingToRelocate: YesNoOrUnknown.YES,
    children: Children.HAS_NOT_AND_DOES_WANT,
    ethnicity: Ethnicity.WHITE,
    drinking: Drinking.NEVER,
    consumables: Consumables.NO_CONSUMABLES,
    politicalBeliefs: PoliticalBeliefs.CONSERVATIVE,
    levelOfEducation: LevelOfEducation.BACHELORS,
    purity: Purity.VIRGIN_WAITING,
    onlyLookingForTraditionalHousehold: YesNoOrUnknown.YES,
    income: Income.SINGLE,
    maritalStatus: MaritalStatus.NEVER_MARRIED,
    activity: Activity.INFREQUENT,
    religion: Religion.CHRISTIANITY,
    bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum!",
    weightUnit: WeightUnit.KG,
    circles: [Circles.Religion.Christianity, Circles.Political.Conservative],
    password: "password1234",
    email: "tina2@gmail.com",
  },
  {
    userId: "3",
    username: "Tina",
    sex: Gender.FEMALE,
    birthDate: new Date(1998, 2, 24),
    weight: 80.23,
    height: 198,
    location: {
      id: "20",
      country: countries[20].country,
      continent: countries[20].continent,
      state: countries[20].states[0],
    },
    willingToRelocate: YesNoOrUnknown.YES,
    children: Children.HAS_NOT_AND_DOES_WANT,
    ethnicity: Ethnicity.WHITE,
    drinking: Drinking.NEVER,
    consumables: Consumables.NO_CONSUMABLES,
    politicalBeliefs: PoliticalBeliefs.LIBERAL,
    levelOfEducation: LevelOfEducation.BACHELORS,
    purity: Purity.VIRGIN_WAITING,
    onlyLookingForTraditionalHousehold: YesNoOrUnknown.YES,
    income: Income.SINGLE,
    maritalStatus: MaritalStatus.NEVER_MARRIED,
    activity: Activity.INFREQUENT,
    religion: Religion.CHRISTIANITY,
    bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum!",
    weightUnit: WeightUnit.KG,
    circles: [Circles.Religion.Christianity, Circles.Political.Conservative],
    password: "password1234",
    email: "tina@gmail.com",
  },
];

export const UsersPreferences = [
  {
    userId: "1",
    username: "Jeremiah",
    sex: Gender.FEMALE,
    birthDate: new Date(1999, 4, 24),
    maxAge: 30,
    minAge: 18,
    selectedCircles: [
      Circles.Religion.Christianity,
      Circles.Political.Conservative,
    ],
  },
];

export const Messages = [
  {
    authorUsername: "Jeremiah",
    recipientUsername: "Tina",
    content: "Heyooooo!",
  },
  { authorUsername: "Tina", recipientUsername: "Jeremiah", content: "Hi!" },
];
